### PR TITLE
Thanh dev

### PR DESCRIPTION
**Pull request by thanhnk1602**
Update readme and gitignore

### CODE REVIEW

**Comment by se7oluti0n** [comment]
**_You created a pull request and accepted it your self :))**_

**Comment by se7oluti0n** [comment]
Also delete your branch after you successfully merge

**Comment by thanhnk1602** [comment]
I create one, I told you on whatsapp. I need someone to check it out. No one checked that and accepted my pull request, so I think , I will accept it. Next time I will use git-cli and wait for someone accepted it

**Comment by se7oluti0n** [comment]
OK, I didn't realize your pull request? I'm going to create a pull request for models diagram. Check it out

**Pull request merged**
